const STATIC = {
  HERO_TITLE: "DON'T KNOW WHERE TO GO?",
  HERO_SUBTITLE: 'YOUR GIRLFRIEND IS HUNGRY AND YOU',
  HERO_TAGLINE: 'Well, let me help you, fella.',
  BANNER_FAVORITE_TITLE: 'FAVORITE RESTAURANTS',
  BANNER_FAVORITE_SUBTITLE:
    'READY TO TAKE YOUR GIRLFRIEND OUT? <a href="#/booking" class="book-now">BOOK NOW</a>.',
  BANNER_FAVORITE_IMAGE: 'images/heros/hero-image_4.jpg',
  BANNER_BOOKING_TITLE: 'BOOKING TITLE',
  BANNER_BOOKING_SUBTITLE: 'BOOKING SUBTITLE',
  BANNER_BOOKING_IMAGE: 'images/heros/hero-image_4.jpg',
};

export default STATIC;
