const TEXTS = {
  HERO_TITLE: "DON'T KNOW WHERE TO GO?",
  HERO_SUBTITLE: 'YOUR GIRLFRIEND IS HUNGRY AND YOU',
  HERO_TAGLINE: 'Well, let me help you, fella.',
  BANNER_FAVORITE_TITLE: 'FAVORITE RESTAURANT TITLE',
  BANNER_FAVORITE_SUBTITLE: 'FAVORITE RESTAURANT SUBTITLE',
};

export default TEXTS;
